[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-sensible"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-sensible.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-yank.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-continuum"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-continuum.git"
    refreshPeriod = "168h"

[".tmux/plugins/vim-tmux-navigator"]
    type = "git-repo"
    url = "https://github.com/christoomey/vim-tmux-navigator.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-floax"]
    type = "git-repo"
    url = "https://github.com/omerxx/tmux-floax.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-thumbs"]
    type = "git-repo"
    url = "https://github.com/fcsonline/tmux-thumbs.git"
    refreshPeriod = "168h"

